config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :user, except: [:index]
  resources :session, only: [:new, :create]

  get "log_out" => "session#log_out", as: :session_log_out

  namespace :admin do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :students, only: [:index]
    resources :teachers, only: [:index]
  end

  namespace :student do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :signup, only: [:new, :create]
  end

  namespace :teacher do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :chat, only: [:index, :create]
    resources :signup, only: [:new, :create]
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability/student.rb
class Ability::Student
  include CanCan::Ability

  def initialize(user)
    
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
  before_action :authenticate_user
  def index
    @page = (params[:page] || 1).to_i
    @page = @page<1? 1 : @page
    @total_students = User.where(administration_id: current_user.administration_id, user_type: "student")
    @pages = (@total_students.count/Float(10)).ceil
    @students = @total_students.offset((@page-1)*10).limit(10)
    @redirect_path = method(:admin_students_path)
  end
end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < ApplicationController
  def index
  end
end

app/controllers/student/signup_controller.rb
class Student::SignupController < ApplicationController
  def new
    @email_identifier = "@" + current_user.administration.email_identifier
    @errors = flash.now[:user_data] || {}
    @user_data = flash.now[:errors] || {}
  end
  def create
    @user_data = user_params || {}
    user = user_params
    @errors = {}
    @email_identifier = "@" + current_user.administration.email_identifier
    user[:user_type] = "student"
    user[:email] = user[:email] + "@" + current_user.administration.email_identifier
    user[:administration_id] = current_user.administration_id
    result = Signing::CreateStudent.call(user: user)
    if result.success?
      redirect_to admin_students_path
    else
      flash.now[:user_data] = @user_data
      flash.now[:errors] = @errors = result['contract.default'].errors
      render :new, status: :unprocessable_entity
    end
  end


  private

  def user_params
    params.require(:student_user).permit(:first_name, :last_name, :personal_email, :email, :password, :confirm_password)
  end
end

app/helpers/student/dashboard_helper.rb
module Student::DashboardHelper
end

app/helpers/student/signup_helper.rb
module Student::SignupHelper
end

app/views/admin/students/_student.html.erb
<%= link_to new_student_signup_path do %>
  <tr class="border-t border-gray-200 hover:bg-gray-100">
    <td class="py-3 px-4"><%= link_to student.email, "#", class:"no-underline" %></td>
    <td class="py-3 px-4"><%= student.first_name %></td>
    <td class="py-3 px-4"><%= student.last_name %></td>
    <td class="py-3 px-4"><%= student.created_at.strftime("%B %d, %Y") %></td>
    <td class="py-3 px-4"><%= student.status %></td>
    <td class="py-3 px-4">
      <%= link_to "Edit", "#", class: "text-primary-color-default py-2 px-4 no-underline" %>
    </td>
  </tr>
<% end %>

app/views/admin/students/index.html.erb
<div class="flex justify-between items-center mx-4 align-middle ">
  <h1>All Students</h1>
  <%= link_to "New Student", new_student_signup_path, class:"text-white font-bold bg-primary-color-default no-underline py-2 px-4 rounded" %>
</div>
<% if @total_students.count >0 %>
  <div class="bg-white shadow-md rounded my-6 mx-4">
    <table class="min-w-full bg-white rounded">
      <thead>
        <tr>
          <th class="w-1/6 py-2 px-4 bg-primary-color-300 rounded-tl font-bold uppercase text-sm text-white text-left">Email</th>
          <th class="w-1/6 py-2 px-4 bg-primary-color-300 font-bold uppercase text-sm text-white text-left">First Name</th>
          <th class="w-1/6 py-2 px-4 bg-primary-color-300 font-bold uppercase text-sm text-white text-left">Last Name</th>
          <th class="w-1/6 py-2 px-4 bg-primary-color-300 font-bold uppercase text-sm text-white text-left">Created At</th>
          <th class="w-1/6 py-2 px-4 bg-primary-color-300 font-bold uppercase text-sm text-white text-left">Status</th>
          <th class="w-1/6 py-2 px-4 bg-primary-color-300 rounded-tr font-bold uppercase text-sm text-white text-left">Actions</th>
        </tr>
      </thead>
      <tbody class="text-gray-700">
        <% @students&.each do |student| %>
          <%= render partial:"student", locals: { student: student } %>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- Pagination -->
  <%= render partial:"common/pagination", locals:{total_count: @total_students.count} %>
<% else %>
  <div class="flex flex-col items-center justify-center", style="height: 80vh;"> <!-- Here I've added style because h-80v is not working. Not sure why-->
    <p class="text-gray-600 font-medium size-5 text-center">No students are present. Add sudents to see them here.</p>
  </div>
<% end %>