config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :user, except: [:index]
  resources :session, only: [:new, :create]

  get "log_out" => "session#log_out", as: :session_log_out

  namespace :admin do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :students, only: [:index]
    resources :teachers, only: [:index]
  end

  namespace :student do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :signup, only: [:new, :create]
  end

  namespace :teacher do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :chat, only: [:index, :create]
    resources :signup, only: [:new, :create]
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @login_data = flash.now[:user_data] || {}
    @errors = flash.now[:errors] || {}
  end

  def create
    @login_data = params[:login_user] || {}
    @errors = {}
    session_status = Session::Create.call(login_user: session_params, session: session)
    if session_status.success?
      if session_status[:user].admin?
        redirect_to admin_dashboard_path
      elsif session_status[:user].teacher?
        redirect_to teacher_dashboard_path
      elsif session_status[:user].student?
        redirect_to student_dashboard_path
      end
    else
      flash.now[:user_data] = @login_data
      flash.now[:errors] = @errors = session_status[:model].errors
      render :new, status: :unprocessable_entity
    end
  end

  def log_out
    # Clear all session data
    reset_session

    redirect_to root_path
  end


  private

  def session_params
    params.require(:login_user).permit(:email, :password)
  end
end

app/views/session/new.html.erb
<div class="h-full" data-controller="session--new">
  <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <%= image_tag("logo.png", alt: "Company Logo", class: "mx-auto h-20 w-auto") %>
      <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Sign in to your account</h2>
    </div>
    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <% if @errors[:password_validation].present? && @errors.details.keys == [:password_validation] %>
        <p class= "text-sm text-red-500"><%= @errors[:password_validation].first %></p>
      <% end %>
      <%= form_with url: session_index_path, method: :post, scope: :login_user, class: "space-y-6" do |form| %>
        <div>
          <%= form.label :email, "Organization Email", id: "em_tag", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2 flex items-center">
            <%= form.text_field :email, type: 'text', value: @login_data[:email], placeholder: "Enter your organization email", class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-7 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-color-default sm:text-sm sm:leading-6" %>
          </div>
          <% if @errors[:email].present? %>
            <%= form.label @errors[:email].first, class: "text-sm text-red-500" %>
          <% end %>
        </div>
        <div>
          <%= form.label :password, "Password", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="relative mt-2 rounded-md shadow-sm">
            <%= form.text_field :password, id:"password", value: @login_data[:password], type: 'password', placeholder: "Enter your password", class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-color-default sm:text-sm sm:leading-6" %>
            <div  id="password_view">
              <i class="fa-regular fa-eye absolute inset-y-0 right-0 flex items-center mr-2 mb-auto mt-auto text-gray-500"></i>
            </div>
          </div>
          <% if @errors[:password].present? %>
            <%= form.label @errors[:password].first, class: "text-sm text-red-500" %>
          <% end %>
        </div>
        <div>
          <%= form.submit "Sign in", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-color-default hover:bg-primary-color-400" %>
        </div>
      <% end %>
    </div>
  </div>
</div>