config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :user, except: [:index]
  resources :session, only: [:new, :create]

  get "log_out" => "session#log_out", as: :session_log_out

  namespace :admin do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :students, only: [:index]
    resources :teachers, only: [:index]
  end

  namespace :student do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :signup, only: [:new, :create]
  end

  namespace :teacher do
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :chat, only: [:index, :create]
    resources :signup, only: [:new, :create]
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability/student.rb
class Ability::Student
  include CanCan::Ability

  def initialize(user)
    
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
  before_action :authenticate_user
  def index
    @page = (params[:page] || 1).to_i
    @page = @page<1? 1 : @page
    @total_students = User.where(administration_id: current_user.administration_id, user_type: "student")
    @pages = (@total_students.count/Float(10)).ceil
    @students = @total_students.offset((@page-1)*10).limit(10)
    @redirect_path = method(:admin_students_path)
  end
end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < ApplicationController
  def index
  end
end

app/controllers/student/signup_controller.rb
class Student::SignupController < ApplicationController
  def new
    @email_identifier = "@" + current_user.administration.email_identifier
    @errors = flash.now[:user_data] || {}
    @user_data = flash.now[:errors] || {}
  end
  def create
    @user_data = user_params || {}
    user = user_params
    @errors = {}
    @email_identifier = "@" + current_user.administration.email_identifier
    user[:user_type] = "student"
    user[:email] = user[:email] + "@" + current_user.administration.email_identifier
    user[:administration_id] = current_user.administration_id
    result = Signing::CreateStudent.call(user: user)
    if result.success?
      redirect_to admin_students_path
    else
      flash.now[:user_data] = @user_data
      flash.now[:errors] = @errors = result['contract.default'].errors
      render :new, status: :unprocessable_entity
    end
  end


  private

  def user_params
    params.require(:student_user).permit(:first_name, :last_name, :personal_email, :email, :password, :confirm_password)
  end
end

app/controllers/teacher/signup_controller.rb
class Teacher::SignupController < ApplicationController
  def new
    @path = method(:teacher_signup_index_path)
    @errors = flash.now[:errors] || {}
    @user_data = flash.now[:user_data] || {}
    @user_data[:email_identifier] = current_user.administration.email_identifier
  end
  def create
    @path = method(:teacher_signup_index_path)
    @user_data = user_params || {}
    user = user_params
    @errors = {}
    @user_data[:email_identifier] = current_user.administration.email_identifier
    user[:user_type] = "teacher"
    user[:email] = user[:email] + "@" + current_user.administration.email_identifier
    user[:administration_id] = current_user.administration_id
    result = Signing::CreateStudent.call(user: user)
    if result.success?
      redirect_to admin_teachers_path
    else
      flash.now[:user_data] = @user_data
      flash.now[:errors] = @errors = result['contract.default'].errors
      render :new, status: :unprocessable_entity
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :personal_email, :email, :password, :confirm_password)
  end
end

app/helpers/student/dashboard_helper.rb
module Student::DashboardHelper
end

app/helpers/student/signup_helper.rb
module Student::SignupHelper
end

app/views/student/signup/new.html.erb
<div class="h-full" data-controller="user--new">
  <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <%= image_tag("logo.png", alt: "Company Logo", class: "mx-auto h-20 w-auto") %>
      <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Sign up to your account</h2>
    </div>
    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <%= form_with url: student_signup_index_path, method: :post, scope: :student_user, class: "space-y-6" do |form| %>
        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
          <div class="sm:col-span-3">
            <%= form.label :first_name, "First Name", class: "block text-sm font-medium leading-6 text-gray-900" %>
            <div class="mt-2 shadow-sm">
              <%= form.text_field :first_name, value: @user_data[:first_name], placeholder: "Enter First Name", class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-color-default sm:text-sm sm:leading-6" %>
            </div>
            <% if @errors[:first_name].present? %>
              <%= form.label @errors[:first_name].first, class: "text-sm text-red-500" %>
            <% end %>
          </div>
          <div class="sm:col-span-3">
            <%= form.label :last_name, "Last Name", class: "block text-sm font-medium leading-6 text-gray-900" %>
            <div class="mt-2 shadow-sm">
              <%= form.text_field :last_name, value: @user_data[:last_name], placeholder: "Enter Last Name", class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-color-default sm:text-sm sm:leading-6" %>
            </div>
            <% if @errors[:last_name].present? %>
              <%= form.label @errors[:last_name].first, class: "text-sm text-red-500" %>
            <% end %>
          </div>
        </div>
        <div>
          <%= form.label :personal_email, "Personal Email", id: "em_tag", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2 shadow-sm">
            <%= form.text_field :personal_email, type: 'email', value: @user_data[:personal_email], placeholder: "Enter your personal email", class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-color-default sm:text-sm sm:leading-6" %>
          </div>
          <% if @errors[:personal_email].present? %>
            <%= form.label @errors[:personal_email].first, class: "text-sm text-red-500" %>
          <% end %>
        </div>
        <div>
          <%= form.label :email, "Organization Email", id: "em_tag", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2 flex items-center">
            <%= form.text_field :email, type: 'text',value: @user_data[:email], placeholder: "Enter your organization email", class: "block w-full rounded-l-md rectangle-r-md border-0 py-1.5 pl-7 pr-7 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-color-default sm:text-sm sm:leading-6" %>
            <p id = "identifier" class="inset-y-0 left-0 p-1.5 items-center mb-auto mt-auto text-gray-500 rectangle-l-md rounded-r-md  border-0 ring-1 ring-inset ring-gray-300 w-auto"><%= @email_identifier %></p>
          </div>
          <% if @errors[:email].present? %>
            <%= form.label @errors[:email].first, class: "text-sm text-red-500" %>
          <% end %>
        </div>
        <div>
          <%= form.label :password, "Password", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="relative mt-2 rounded-md shadow-sm">
            <%= form.text_field :password, id:"password", type: 'password', value: @user_data[:password], placeholder: "Enter your password", class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-color-default sm:text-sm sm:leading-6" %>
            <div  id="password_view">
              <i class="fa-regular fa-eye absolute inset-y-0 right-0 flex items-center mr-2 mb-auto mt-auto text-gray-500"></i>
            </div>
          </div>
          <% if @errors[:password].present? %>
            <%= form.label @errors[:password].first, class: "text-sm text-red-500" %>
          <% end %>
        </div>
        <div>
          <%= form.label :confirm_password, "Confirm Password", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="relative mt-2 rounded-md shadow-sm">
            <%= form.text_field :confirm_password,id: "confirm_password", type: 'password', value: @user_data[:confirm_password], placeholder: "Re-enter your password", class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-color-default sm:text-sm sm:leading-6" %>
            <div id="confirm_password_view">
              <i class="fa-regular fa-eye absolute inset-y-0 right-0 flex items-center mr-2 mb-auto mt-auto text-gray-500"></i>
            </div>
          </div>
          <% if @errors[:confirm_password].present? %>
            <%= form.label @errors[:confirm_password].first, class: "text-sm text-red-500" %>
          <% end %>
        </div>
        <div>
          <%= form.submit "Sign up", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-color-default hover:bg-primary-color-400" %>
        </div>
      <% end %>
    </div>
  </div>
</div>